#!/usr/bin/env bash
#
# Copyright 2009-2024 Joshua Bronson. All rights reserved.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# shellcheck disable=SC2086,SC1091


set -euo pipefail

log() {
  >&2 printf "> %s\n" "$@"
}


main() {
  local -r dotslash="$(dirname "$(readlink -f "$0")")"
  source "$dotslash/dev.env"
  for cmd in "$DEFAULT_PY" uv pre-commit; do
    if ! type "$cmd"; then
      log "Error: No '$cmd' on PATH. Hint: Check /init_dev_env and try again."
      exit 1
    fi
  done

  local -r pip_compile="uv pip compile --upgrade --universal"
  for depset in test docs dev; do
    $pip_compile "dev-deps/$depset.in" -o "dev-deps/$depset.txt" >/dev/null
  done
  uv pip sync dev-deps/*.txt
  uv pip show -q bidict || uv pip install -e "$BIDICT_ROOT_DIR"
  log "Upgrading PyPI dependencies: Done"
  log
  log "Upgrading pre-commit hooks..."
  pre-commit autoupdate
  log "Done."
  log
  log "Reminders:"
  log " - Check release notes of upgraded packages for anything that affects bidict."
  log " - Ensure tests pass for all supported Python versions."
  log " - Check output for any new warnings, not just test failures."
  log " - Ensure 'pre-commit run --all-files' still succeeds."
}

main
