---
# https://docs.readthedocs.io/en/latest/config-file/
version: 2

formats:
  - htmlzip

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements/docs.txt
