---
# https://docs.readthedocs.io/en/latest/config-file/
version: 2

formats:
  - htmlzip

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"
  # https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-uv
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv sync --group=docs
    - .venv/bin/python -m sphinx -TWn --keep-going -b html -d docs/_build/doctrees docs $READTHEDOCS_OUTPUT/html
