# https://docs.readthedocs.io/en/latest/config-file/
version: 2

formats:
  - htmlzip

build:
  image: latest

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
