#!/usr/bin/env bash
#
# Copyright 2009-2024 Joshua Bronson. All rights reserved.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# shellcheck disable=SC1091

set -euo pipefail

declare -r hint="Hint: Use 'nix develop' to bootstrap a development environment"

for cmd in uv pre-commit; do
  if ! type "$cmd"; then
    >&2 echo "Error: No '$cmd' on PATH. $hint"
    exit 1
  fi
done
pre-commit install -f

uv sync
echo "Development virtualenv initialized and activated"
