- Thanks to Gregory Ewing for the name.

- Thanks to Terry Reedy for suggesting the slice syntax
  (it was fun while it lasted).

- Thanks to Raymond Hettinger for suggesting namedbidict
  and pointing out various caveats.

- Thanks to Francis Carr for the idea of storing the inverse bidict.

- Thanks to Brianna Laugher and Adopt Pytest Month for choosing bidict
  as one of Adopt Pytest Month 2015's selected projects.

- Thanks to Tom Viner for all the help as bidict's mentor
  during Adopt Pytest Month 2015.

- Thanks to the Pytest team and to David MacIver for the great testing tools.

- Thanks to Daniel Pope for various suggestions enhancing bidict's Python zen.
