name: release to pypi.org

"on":
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-24.04
    steps:
      - name: check out source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25
      - name: build distributions
        run: nix develop .#build --command uv build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

permissions:
  contents: read
