# This name appears as the text in the build badge: https://github.com/jab/bidict/actions/workflows/test.yml/badge.svg
name: tests

"on":
  workflow_dispatch:
    inputs:
      hypothesis_profile:
        type: choice
        description: (optional)
        options:
        - default
        - more-examples
  schedule:
    - cron: "15 16 * * *"
  push:
    branches:
      - main
      - dev
      - deps
  pull_request:
    branches:
      - main

env:
  FORCE_COLOR: "1"
  PYTEST_ADDOPTS: "--benchmark-disable"

jobs:
  test-all:
    name: ${{ matrix.python }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: "3.14"
            shell: test314
            enable_coverage: true
          - python: "3.13"
            shell: test313
          - python: "3.12"
            shell: test312
          - python: "3.11"
            shell: test311
            # bidict/_typing.py's `typing`/`typing_extensions` imports branch on python<3.12
            enable_coverage: true
          - python: "pypy-3.11"
            shell: testPyPy311
    steps:
      - name: check out source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25
      - name: cache .mypy_cache dir
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: .mypy_cache
          key: mypy
      - name: set hypothesis profile
        run: |
          hypothesis_profile=${{ github.event.inputs.hypothesis_profile || (github.event_name == 'schedule' && 'more-examples' || 'default') }}
          echo PYTEST_ADDOPTS="$PYTEST_ADDOPTS --hypothesis-profile=$hypothesis_profile" >> "$GITHUB_ENV"
      - name: cache .hypothesis dir
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: .hypothesis
          key: hypothesis|${{ runner.os }}|${{ matrix.python }}
      - name: maybe enable coverage
        if: matrix.enable_coverage
        run: |
          echo RUN_PYTEST_CMD="coverage run -m pytest" >> "$GITHUB_ENV"
      - name: run mypy and pytest
        run: |
          nix develop .#${{ matrix.shell }} --command bash -c "
            set -euo pipefail
            if python -m mypy -V; then mypy bidict tests; else echo 'Skipping mypy (not available)'; fi
            \${RUN_PYTEST_CMD:-pytest}
          "
      - name: combine and show any collected coverage
        if: matrix.enable_coverage
        run: |
          nix develop .#${{ matrix.shell }} --command bash -c '
            coverage combine
            coverage debug data
            coverage report
          '
      - name: maybe upload to Codecov  # https://github.com/codecov/codecov-action
        if: matrix.enable_coverage
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          verbose: true
          fail_ci_if_error: false  # https://github.com/codecov/codecov-action/issues/557


permissions:
  contents: read
